name: Review configuration changes

on:
  pull_request:
    branches:
      - main
    paths:
      - 'settings.json'

jobs:
  pr-review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.4

    - name: Install jq
      run: sudo apt-get install jq

    - name: Extract JSON diff
      run: |
        # PRのbaseとhead間の差分を取得
        git diff HEAD^ HEAD -- 'data/**/*.json' > changes.diff
        # 差分ファイルからJSONデータを抽出（例としてjqを使用）
        cat changes.diff | jq . > extracted_data.json
        
    - name: Print extracted JSON
      run: cat extracted_data.json
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Pythonのバージョン指定
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

